
SPEC: tour_scheduling_nonmandatory.csv
<<<<<<< HEAD:activitysim/examples/prototype_mtc_extended/configs/non_mandatory_tour_scheduling.yaml
COEFFICIENTS: tour_scheduling_nonmandatory_coefficients.csv
=======
COEFFICIENTS: tour_scheduling_nonmandatory_coeffs.csv
>>>>>>> BayDAG:activitysim/examples/placeholder_psrc/configs/non_mandatory_tour_scheduling.yaml

LOGIT_TYPE: MNL

preprocessor:
  SPEC: non_mandatory_tour_scheduling_annotate_tours_preprocessor
  DF: non_mandatory_tours
  TABLES:
    - land_use
    - joint_tour_participants
<<<<<<< HEAD:activitysim/examples/prototype_mtc_extended/configs/non_mandatory_tour_scheduling.yaml
    - school_escort_tours
=======
>>>>>>> BayDAG:activitysim/examples/placeholder_psrc/configs/non_mandatory_tour_scheduling.yaml

SIMULATE_CHOOSER_COLUMNS:
  - ptype
  - num_children
  - roundtrip_auto_time_to_work
  - num_mand
  - num_escort_tours
  - num_non_escort_tours
  - adult
